export const CardInput = [
  {
    id: "a",
    title: "Lakavimas",
    duration: "Trukme: 20h",
    price: "Kaina: 200eur",
    content:
      "uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labor uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labor uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labor uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore uatur labore,ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labor ",
  },
  {
    id: "b",
    title: "Lakavimas2",
    duration: "Trukme: 20h1",
    price: "Kaina: 200eur1",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },
  {
    id: "c",
    title: "Lakavimas3",
    duration: "Trukme: 20h2",
    price: "Kaina: 200eur2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },
  {
    id: "d",
    title: "Lakavimas4",
    duration: "Trukme: 20h3",
    price: "Kaina: 200eur3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },
  {
    id: "e",
    title: "Lakavimas4",
    duration: "Trukme: 20h3",
    price: "Kaina: 200eur3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },
  {
    id: "f",
    title: "Lakavimas4",
    duration: "Trukme: 20h3",
    price: "Kaina: 200eur3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },
  {
    id: "g",
    title: "Lakavimas4",
    duration: "Trukme: 20h3",
    price: "Kaina: 200eur3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },

  {
    id: "h",
    title: "Lakavimas4",
    duration: "Trukme: 20h3",
    price: "Kaina: 200eur3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi a, maxime soluta error quibusdam, consequatur labore, qui amet eum quis accusantium aliquam illum eligendi quisquam inventore corrupti ut hic unde iste. Corporis quos voluptatibus in. Culpa ducimus alias earum adipisci incidunt quam aspernatur, consectetur eaque deleniti quo eius debitis soluta.",
  },
];
